---
- name: Fetch environments 
  uri:
    method: GET
    validate_certs: no
    return_content: yes
    url: "{{ automation }}/project/{{ semaphore_project_id }}/environment"
    body_format: json
    status_code: 200
    headers:
      Cookie: "semaphore={{ semaphore_token }}"
  ignore_errors: yes 
  register: environments

- name: set production environment Id 
  set_fact: 
    "env_production_id": "{{ item.id }}"
  when: 
    - item.name == "Production"
  with_items: "{{ environments.json }}"

- name: Create production Environment
  uri:
    method: POST
    validate_certs: no
    return_content: yes
    url: "{{ automation }}/project/{{ semaphore_project_id }}/environment"
    body_format: json
    body: '{ "name": "Production", "project_id": {{ semaphore_project_id }}, "password": "string", "json": "{}" }'
    status_code: 204
    headers:
      Cookie: "semaphore={{ semaphore_token }}"
  when: 
    - env_production_id is not defined 

- name: Update production Environment
  uri:
    method: PUT
    validate_certs: no
    return_content: yes
    url: "{{ automation }}/project/{{ semaphore_project_id }}/environment/{{ env_production_id }}"
    body_format: json
    body: '{ "name": "Production", "id": {{ env_production_id }},"project_id": {{ semaphore_project_id }}, "password": "string", "json": "{}" }'
    status_code: 204
    headers:
      Cookie: "semaphore={{ semaphore_token }}"
  when: 
    - env_production_id is defined 
  
- name: Fetch environments after created the new env
  uri:
    method: GET
    validate_certs: no
    return_content: yes
    url: "{{ automation }}/project/{{ semaphore_project_id }}/environment"
    body_format: json
    status_code: 200
    headers:
      Cookie: "semaphore={{ semaphore_token }}"
  ignore_errors: yes 
  register: environments
  when:
    - env_production_id is not defined 

- name: set production environment Id 
  set_fact: 
    "env_production_id": "{{ item.id }}"
  when: 
    - env_production_id is not defined 
    - item.name == "Production"
  with_items: "{{ environments.json }}"
